import { test, expect } from '@playwright/test';
test('real Ollama + MCP + domain + pgvector + human approval',async({page})=>{
  test.skip(process.env.FABOPS_LIVE !== '1', 'Requires running local services');
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('/');
  await expect(page.locator('app-root')).toHaveAttribute('ng-version', /^21\./);
  await expect(page.getByRole('button',{name:'開始調查'})).toBeEnabled();
  const responsePromise=page.waitForResponse(response=>response.url().endsWith('/api/investigate'),{timeout:650_000});
  await page.getByRole('button',{name:'開始調查'}).click();
  const response=await responsePromise;expect(response.status()).toBe(200);
  const run=await response.json();expect(run.mode).toBe('ollama-agent');expect(run.evidence.length).toBeGreaterThan(0);expect(run.ticket).toBeTruthy();
  await expect(page.getByText('Ticket 草稿待審查')).toBeVisible();
  await page.getByRole('button',{name:run.findings.steps[0].citations[0],exact:true}).first().click();
  await expect(page).toHaveURL(/#\/operations$/);
  const approve=page.getByRole('button',{name:'核准模擬工單'});await expect(approve).toBeDisabled();
  await page.getByRole('checkbox').check();await approve.click();
  await expect(page.getByText('模擬工單已核准')).toBeVisible({timeout:10_000});
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:'../artifacts/live-workflow-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'../artifacts/live-workflow-mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.getByRole('link',{name:'工單與稽核'}).click();
  await expect(page.getByText('ticket_approved').first()).toBeVisible();
  await page.getByRole('link',{name:'知識檢索'}).click();
  await page.getByRole('textbox',{name:'搜尋 SOP'}).fill('temperature drift sensor calibration');
  const searchPromise=page.waitForResponse(response=>response.url().endsWith('/api/search'));
  await page.getByRole('button',{name:'搜尋',exact:true}).click();
  const searchResponse=await searchPromise;
  expect(searchResponse.request().postDataJSON()).toEqual({query:'temperature drift sensor calibration'});
  await expect(page.getByText('hybrid-pgvector')).toBeVisible();
  await expect(page.locator('.source').first()).toContainText('SOP-TEMP-02');
  await page.getByRole('link',{name:'值班交接'}).click();
  const handoverPromise=page.waitForResponse(response=>response.url().endsWith('/api/handover'),{timeout:190_000});
  await page.getByRole('button',{name:'產生交接摘要'}).click();
  const handover=await (await handoverPromise).json();expect(handover.mode).toBe('ollama');
  await expect(page.locator('.handover')).not.toBeEmpty();
  await expect(page.getByText('INC-1001',{exact:true})).toBeVisible();
  await page.getByRole('link',{name:'事故應變'}).click();
  await expect(page.getByText('模擬工單已核准')).toBeVisible();
  expect(errors).toEqual([]);
});
